{% set name = "furo" %}
{% set version = "2021.11.12.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/furo-{{ version }}.tar.gz
  sha256: 26f1a00c6da12d58afd5b9fafde8c6f636912961c8c2af7e70f4334c36d44f96

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - flit-core >=2,<4
  run:
    - python >=3.6
    - sphinx >=4
    - beautifulsoup4
    - myst-parser
    - sphinx-inline-tabs


test:
  imports:
    # One more reason to dislike type-hints
    # This is a dirty hack because sphinx.application
    # isn't available with a simple `import sphinx`
    - sphinx.application
    - furo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pradyunsg/furo
  summary: A clean customisable Sphinx documentation theme.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gforsyth
